name: CI

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        target:
          [
            x86_64-pc-windows-msvc,
            i686-pc-windows-msvc,
            x86_64-apple-darwin,
            aarch64-apple-darwin,
          ]
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: windows-latest
            target: i686-pc-windows-msvc
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Rename executable
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            mv target/${{ matrix.target }}/release/http-status-checker.exe target/${{ matrix.target }}/release/http-status-checker-${{ matrix.target }}.exe
          else
            mv target/${{ matrix.target }}/release/http-status-checker target/${{ matrix.target }}/release/http-status-checker-${{ matrix.target }}

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/${{ matrix.target }}/release/http-status-checker-${{ matrix.target }}${{ matrix.os == 'windows-latest' && '.exe' || '' }}
